package scanner;


public enum Token {
    COMMA, SEMICOLON, PLUS_PLUS, MINUS_MINUS, GREATER_OR_EQUAL_THAN, GREATER_THAN,
    LESS_OR_EQUAL_THAN, LESS_THAN,
    LESS_GREATER, ASSIGN, PLUS, MINUS, TIMES, DIV, PARENT, COL, COLON_ASSIGN, PERIOD,
    COLON, SUM_ASSIGN, MINUS_ASSIGN,
    TIMES_ASSIGN, DIV_ASSIGN, LEFT, RIGHT, RIGHT_ASSIGN, LEFT_ASSIGN, AND, ARRAY,
    BEGIN, BOOLEAN, BYTE, CASE, CHAR, CONST, DO, 
    DOWNTO, ELSE, END, FALSE, FILE, FOR, FORWARD, FUNCTION, GOTO, IF, IN, INLINE, INT,
    LABEL, LONGINT, MOD, NIL, OF, PACKED,
    PROCEDURE, PROGRAM, READ, REAL, RECORD, REPEAT, SET, SHORTINT, STRING, THEN, TO,
    TRUE, TYPE, UNTIL, VAR, WHILE, WITH, WRITE,
    NOT, OR, XOR, DIV_WORD, ID,  ERROR, ERROR_ID,  STRING_LITERAL, CHAR_LITERAL, FLOAT_LITERAL,
    INT_LITERAL, CHAR_MADE_INT_LITERAL;
    
}
 

